[package]
name = "risc0-circuit-keccak-test-methods"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-circuit-keccak = { path = "../..", default-features = false }

[dependencies.risc0-zkvm]
git = "https://github.com/risc0/risc0.git"
rev = "093f46925a0366d72df505256d35c54a033ddad0"
default-features = false
features = ["std"]

[dependencies.risc0-zkvm-platform]
git = "https://github.com/risc0/risc0.git"
rev = "093f46925a0366d72df505256d35c54a033ddad0"
default-features = false
features = ["unstable"]
