[workspace]
resolver = "2"
members = [
  "risc0/circuit/rv32im-v2",
  "risc0/circuit/rv32im-v2-sys",
  "zirgen/circuit/fib",
  # "zirgen/circuit/keccak",
  # "zirgen/circuit/keccak-sys",
  "zirgen/dsl",
]

[workspace.dependencies]
risc0-circuit-keccak = { path = "zirgen/circuit/keccak" }
risc0-circuit-keccak-sys = { path = "zirgen/circuit/keccak-sys" }
risc0-circuit-rv32im-v2 = { path = "risc0/circuit/rv32im-v2" }
risc0-circuit-rv32im-v2-sys = { path = "risc0/circuit/rv32im-v2-sys" }
risc0-zirgen-dsl = { path = "zirgen/dsl" }
sppark = "0.1.8"

[workspace.dependencies.risc0-binfmt]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-build]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-build-kernel]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-circuit-recursion]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-core]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-sys]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-zkp]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-zkvm]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[workspace.dependencies.risc0-zkvm-platform]
git = "https://github.com/risc0/risc0.git"
rev = "3c20ddcb2f5a707115d1cea896fb375818d798cf"
default-features = false

[profile.bench]
lto = true

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3


[patch.'https://github.com/risc0/risc0.git']
risc0-binfmt = { path = "/Users/flaub/src/risczero/risc0/risc0/binfmt" }
risc0-build = { path = "/Users/flaub/src/risczero/risc0/risc0/build" }
risc0-build-kernel = { path = "/Users/flaub/src/risczero/risc0/risc0/build_kernel" }
risc0-circuit-rv32im = { path = "/Users/flaub/src/risczero/risc0/risc0/circuit/rv32im" }
risc0-circuit-recursion = { path = "/Users/flaub/src/risczero/risc0/risc0/circuit/recursion" }
risc0-core = { path = "/Users/flaub/src/risczero/risc0/risc0/core" }
risc0-sys = { path = "/Users/flaub/src/risczero/risc0/risc0/sys" }
risc0-zkp = { path = "/Users/flaub/src/risczero/risc0/risc0/zkp" }
risc0-zkvm = { path = "/Users/flaub/src/risczero/risc0/risc0/zkvm" }
risc0-zkvm-methods = { path = "/Users/flaub/src/risczero/risc0/risc0/zkvm/methods" }
risc0-zkvm-platform = { path = "/Users/flaub/src/risczero/risc0/risc0/zkvm/platform" }
