[package]
name = "risc0-circuit-keccak-test-methods"
version = "0.1.0"
edition = "2021"

[workspace]

[workspace.dependencies.risc0-zkvm]
git = "https://github.com/risc0/risc0.git"
rev = "4b8bf2b08298285ec6c801e4d5a34bcfd426d682"
default-features = false

[dependencies]
risc0-circuit-keccak = { path = "../..", default-features = false }
risc0-zkvm = { workspace = true, default-features = false }
